name: Beta Build

on:
  push:
    branches: [ main ]

jobs:
  beta:
    runs-on: macos-15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Clone fastlane-match repository
      uses: actions/checkout@v4
      with:
        repository: wemakethingstoo/fastlane-match
        path: fastlane-match
        token: ${{ secrets.GH_TOKEN}}
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
        
    - name: Install dependencies
      run: bundle install
    - name: Run fastlane beta
      run: |
        git config --global credential.helper store
        echo "https://x-access-token:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
        bundle exec fastlane beta