name: Beta Build

on:
  push:
    branches: [ main ]

jobs:
  beta:
    runs-on: macos-15
    concurrency:
      group: beta-build-group
      cancel-in-progress: false
    permissions:
      contents: write
      actions: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Clone fastlane-match repository
      uses: actions/checkout@v4
      with:
        repository: wemakethingstoo/fastlane-match
        path: fastlane-match
        token: ${{ secrets.GH_TOKEN}}
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
        
    - name: Install dependencies
      run: bundle install
      
    - name: Run fastlane beta
      continue-on-error: true
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
        ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
        ASC_KEY_P8: ${{ secrets.ASC_KEY_P8 }}
      run: |
        git config --global credential.helper store
        echo "https://x-access-token:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
        bundle exec fastlane beta

  
    - name: Commit Incremented Version Back
      run: |
        # Get the new version and build number from project.pbxproj
        BUILD_VERSION=$(grep -m 1 "MARKETING_VERSION = " Fishtank.xcodeproj/project.pbxproj | sed 's/.*MARKETING_VERSION = \([^;]*\);.*/\1/')
        BUILD_NUMBER=$(grep -m 1 "CURRENT_PROJECT_VERSION = " Fishtank.xcodeproj/project.pbxproj | sed 's/.*CURRENT_PROJECT_VERSION = \([^;]*\);.*/\1/')
        echo "Build version: $BUILD_VERSION"
        echo "Build number: $BUILD_NUMBER"
        
        # Configure git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Add and commit the version change
        git add Fishtank.xcodeproj
        git commit -m "Bump iOS version $BUILD_VERSION build $BUILD_NUMBER [skip ci]"
        git pull origin main --rebase
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
