name: Ensure Fastlane Match

# This workflow makes sure that https://github.com/wemakethingstoo/fastlane-match
# Is up to date with its Matchfile

on:
  push:
    branches: [ main ]

jobs:
  match:
    runs-on: macos-latest
    strategy:
      matrix:
        match_type: [development, appstore]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Clone fastlane-match repository
      uses: actions/checkout@v4
      with:
        repository: wemakethingstoo/fastlane-match
        path: fastlane-match
        token: ${{ secrets.GH_TOKEN}}

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: false

    - name: Copy Gemfile to fastlane-match directory
      run: |
        cp Gemfile fastlane-match/
        cp Gemfile.lock fastlane-match/

    - name: Install dependencies
      working-directory: fastlane-match
      run: |
        bundle install

    - name: Run fastlane match for ${{ matrix.match_type }}
      working-directory: fastlane-match
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
        ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
        ASC_KEY_P8: ${{ secrets.ASC_KEY_P8 }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      run: |
        git config --global credential.helper store
        echo "https://x-access-token:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
        bundle exec fastlane match ${{ matrix.match_type }}
